server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
  data:
    mongodb:
      database: xc_fs
      uri: mongodb://root:root@192.168.42.130:27017
      authentication-database: admin
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 192.168.42.120:22122 #TrackerList参数,支持多个
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50101/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1