server:
  port: ${PORT:40100}
spring:
  application:
    name: xc-service-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.42.120:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50101/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ribbon:
  ConnectTimeout: 5000 #ribbon连接超时时长
  ReadTimeout: 6000 #ribbon读取超时时长
  maxAutoRetries: 0 #当前服务器重试次数
  maxAutoRetriesNextServer: 1 #切换服务重试次数