server:
  port: 31002
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@192.168.42.130:27017
      authentication-database: admin
      database: xc_cms
  rabbitmq:
    host: 192.168.42.130
    port: 5672
    username: xuecheng
    password: xuecheng
    virtual-host: /xuecheng
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1