server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://192.168.42.130:3306/xc_course?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5 #初始建立连接数量
      min-idle: 5 #最小连接数量
      max-active: 20 #最大连接数量
      max-wait: 10000 #获取连接最大等待时间，毫秒
      test-on-borrow: true #申请连接时检测连接是否有效
      test-while-idle: false #归还连接时检测连接是否有效
      time-between-eviction-runs-millis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      min-evictable-idle-time-millis: 300000 #连接在连接池的最小生存时间（毫秒）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuecheng.framework.domain.course
pagehelper:
  reasonable: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50101/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
course:
  publish:
    siteId: 5a751fab6abb5044e0d19ea1
    templateId: 5f279ebf7191e54cbceef497
    previewUrl: http://www.xuecheng.com/cms/preview/
    pageWebPath: /course/detail/
    pagePhysicalPath: H:\\integrated_project\\xc-ui-pc-static-portal\\course\\detail\\
    dataUrlPre: http://localhost:31200/course/courseview/