server:
  port: 50201
  servlet:
    context-path: /api
spring:
  application:
    name: xc-govern-gateway
  redis:
    host: 192.168.42.130
    port: 6379
    timeout: PT5S
    jedis:
      pool:
        max-active: 3
        max-idle: 3
        min-idle: 1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50101/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ribbon:
  MaxAutoRetries: 0 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
zuul:
  routes:
    xc‐service‐learning: #路由名称，名称任意，保持所有路由名称唯一
      path: /learning/**
      serviceId: xc-service-learning #指定服务id，从Eureka中找到服务的ip和端口
      strip‐prefix: false
    manage‐course:
      path: /course/**
      serviceId: xc-service-manage-course
      strip‐prefix: false
    manage‐cms:
      path: /cms/**
      serviceId: xc-service-manage-cms
      strip‐prefix: false
    manage‐sys:
      path: /sys/**
      serviceId: xc-service-manage-sys
      strip‐prefix: false
    service‐ucenter:
      path: /ucenter/**
      serviceId: xc-service-ucenter
      strip‐prefix: false
    xc‐service‐manage‐order:
      path: /order/**
      serviceId: xc-service-manage-order
      strip‐prefix: false
  sensitive-headers:
  add-host-header: true